name: My Second workflow
on:
  pull_request: 
    branches: [main]

jobs:
  builds2:
    runs-on: ubuntu-20.04

    steps:
    - name: Greeting steps
      run: echo "Hello hansum"

    - name: Checkout my codes
      uses: actions/checkout@v4
    
    - name: Print content of repository
      run: ls

    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Check version of Python
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Testing with Pytest
      run: |
        pytest - v -cov --junitxml=report.xml

    - name: Checkout Hidden Repo
      uses: actions/checkout@v4
      with:
        repository: ZuhailiAminUOB/hiddenrepo
        path: hiddenfolder
        token: ${{ secrets.UOBSECRET }}

    - name: Print out hidden things
      run: |
        ls
        cd hiddenfolder
        ls
